name: CMake
on: [push]
jobs:
  build-and-test-linux-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Build Folder
      run: cmake -E make_directory ${{github.workspace}}/build
    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake ${{github.workspace}}
    - name: CMake Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build .
    - name: Run Test
      working-directory: ${{github.workspace}}/build
      run: ctest
